#!/usr/bin/env bash
#
# Run xtensa-lx106-elf container

if [[ "$0" != "${BASH_SOURCE[0]}" ]]; then
  echo "$(basename -- "${BASH_SOURCE[0]}"): error:" \
       'script must not be sourced' >&2
  return 1
fi

readonly SCRIPT_NAME=$(basename -- "${BASH_SOURCE[0]}")
readonly BASE_DIRECTORY=$(cd "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)

source "${BASE_DIRECTORY}/scripts/config.sh"
source "${BASE_DIRECTORY}/scripts/util.sh"

# usage: usage ["printer"]
usage() {
  ${1:-print_raw} "usage: ${SCRIPT_NAME} [-h] [-v] [-n] [-d DATA_DIRECTORY]" \
                  '[-t TAG] ARGS...'
}

# usage: full_usage ["printer"]
full_usage() {
  local printer=${1:-print_raw}

  usage "${printer}"
  ${printer}
  ${printer} 'Run script for xtensa-lx106-elf development container'
  ${printer}
  ${printer} 'arguments:'
  ${printer} '  -h                    show this help message and exit'
  ${printer} '  -v                    show version information and exit'
  ${printer} '  -n                    don'"'"'t run docker and just print the'
  ${printer} '                        command instead'
  ${printer} '  -d DATA_DIRECTORY     mount point for /mnt/data inside the'
  ${printer} '                        container'
  ${printer} '  -t TAG                the tag of the image to run'
  ${printer} '  ARGS...               the command to run in the container'
  ${printer}
  ${printer} 'environment variables:'
  ${printer} '  NAME                  the name of the container to run'
  ${printer} '  TAG                   the tag of the container'
  ${printer} '  MOUNT                 the mount point for /mnt/data inside the'
  ${printer} '                        container'
  ${printer} '  DOCKER                the location of the docker binary'
  ${printer}
  ${printer} 'environment variables can be overridden by normal arguments'
}

# usage: run_image "name" "tag" "mountpoint" args...
run_image() {
  # Default run arguments
  local arguments=(--rm --interactive --tty)

  # Add volume to arguments if we need to
  if [[ -n "$3" ]]; then
    arguments+=(-v "$4:/mnt/data")
  fi

  # Add name to arguments
  arguments+=("$1:$2")

  # Remove the first four arguments from the argument list so we're left with
  # just args
  shift 3

  # If there are any arguments left, add them to the command
  if [[ "$#" -gt 0 ]]; then
    arguments+=("$@")
  fi

  # Run docker with the provided arguments
  run_docker run "${arguments[@]}"
}

# usage: main [-h] [-v] [-n] [-d DATA_DIRECTORY] [-t TAG] ARGS...
main() {
  local print_version=0
  local executor=run_image
  local mount=${MOUNT}
  local tag=${TAG}

  while getopts ':hvnd:t:' OPT; do
    case ${OPT} in
      h) full_usage; return 0 ;;
      v) print_version=1 ;;
      n) executor="mock_run_docker run_image" ;;
      d) mount=${OPTARG} ;;
      t) tag=${OPTARG} ;;
      ?) error "illegal option: ${OPTARG}"; usage error_raw; return 1 ;;
    esac
  done

  # Print version if needed
  if [[ "${print_version}" = 1 ]]; then
    print_version_info "${NAME}" "${tag}"
    return 0
  fi

  # Ensure the mount point is valid
  if [[ -n "${mount}" && "${mount}" = "${mount#/}" ]]; then
    error 'mount point must be absolute'
    return 1
  fi

  # Check whether or not COMMAND was provided
  if [[ $((OPTIND - 1)) = $# ]]; then
    error 'missing ARGS'
    usage error_raw
    return 1
  fi

  # Remove everything leading up to COMMAND argument
  shift $((OPTIND - 1))

  # Run the image
  ${executor} "${NAME}" "${tag}" "${mount}" "$@"
}

main "$@"
exit $?
